version: "3.9"

services:
  app:
    image: receiver
    container_name: receiver_dev
    profiles: ["dev"]
    build:
      context: ./
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules #empty mount to not overwrite node_modules
    environment:
      - NODE_ENV="development"

  nginx:
    image: nginx:latest
    container_name: receiver_nginx
    profiles: ["prod"]
    volumes:
      - $PWD/dist:/usr/share/nginx/html
    restart: unless-stopped
    network_mode: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.receiver.rule=Host(`receiver.agentzhao.me`)"
      - "traefik.http.routers.receiver.tls=true"
      - "traefik.http.routers.receiver.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.receiver.entrypoints=websecure"
      - "traefik.port=80"
